### ISSUE TITLE
Dead or Alive?

### ISSUE THREAD

**Issue by uhlhosting** [GCS-uno/gcs_uno_server#1]
If this project is dead please archive it, I am trying in past 3 hours to get it up and running, tried 3 different ubuntu versions from 20.10 downwards to 18.04 the best I got to its this point:

```
ubuntu@gcs:~/gcs_uno_server$ pm2 status
┌─────┬─────────────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name                │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼─────────────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0   │ drone-udp-server    │ default     │ 1.0.0   │ fork    │ 4915     │ 8s     │ 5    │ online    │ 0%       │ 47.3mb   │ ubuntu   │ disabled │
│ 1   │ drones-server       │ default     │ 1.0.0   │ fork    │ 0        │ 0      │ 105  │ errored   │ 0%       │ 0b       │ ubuntu   │ disabled │
│ 2   │ gcs-tcp-server      │ default     │ 1.0.0   │ fork    │ 4928     │ 8s     │ 5    │ online    │ 0%       │ 46.9mb   │ ubuntu   │ disabled │
│ 3   │ io-server           │ default     │ 1.0.0   │ fork    │ 0        │ 0      │ 90   │ errored   │ 0%       │ 0b       │ ubuntu   │ disabled │
└─────┴─────────────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
ubuntu@gcs:~/gcs_uno_server$ pm2 logs
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/home/ubuntu/.pm2/pm2.log last 15 lines:
PM2        | 2021-03-03T04:51:37: PM2 log: App [drones-server:1] starting in -fork mode-
PM2        | 2021-03-03T04:51:37: PM2 log: App [drones-server:1] online
PM2        | 2021-03-03T04:51:37: PM2 log: App [io-server:3] exited with code [1] via signal [SIGINT]
PM2        | 2021-03-03T04:51:37: PM2 log: App [io-server:3] starting in -fork mode-
PM2        | 2021-03-03T04:51:37: PM2 log: App [io-server:3] online
PM2        | 2021-03-03T04:51:37: PM2 log: App [drones-server:1] exited with code [1] via signal [SIGINT]
PM2        | 2021-03-03T04:51:37: PM2 log: Script /home/ubuntu/gcs_uno_server/servers/drones-server.js had too many unstable restarts (16). Stopped. "errored"
PM2        | 2021-03-03T04:51:38: PM2 log: App [io-server:3] exited with code [1] via signal [SIGINT]
PM2        | 2021-03-03T04:51:38: PM2 log: App [io-server:3] starting in -fork mode-
PM2        | 2021-03-03T04:51:38: PM2 log: App [io-server:3] online
PM2        | 2021-03-03T04:51:38: PM2 log: App [io-server:3] exited with code [1] via signal [SIGINT]
PM2        | 2021-03-03T04:51:38: PM2 log: App [io-server:3] starting in -fork mode-
PM2        | 2021-03-03T04:51:38: PM2 log: App [io-server:3] online
PM2        | 2021-03-03T04:51:38: PM2 log: App [io-server:3] exited with code [1] via signal [SIGINT]
PM2        | 2021-03-03T04:51:38: PM2 log: Script /home/ubuntu/gcs_uno_server/servers/io-server.js had too many unstable restarts (16). Stopped. "errored"

/home/ubuntu/.pm2/logs/drones-server-out.log last 15 lines:
/home/ubuntu/.pm2/logs/io-server-out.log last 15 lines:
/home/ubuntu/.pm2/logs/drone-udp-server-error.log last 15 lines:
0|drone-ud | Creating a pool connected to localhost:28015
0|drone-ud | Creating a pool connected to localhost:28015
0|drone-ud | Creating a pool connected to localhost:28015
0|drone-ud | Creating a pool connected to localhost:28015
0|drone-ud | Creating a pool connected to localhost:28015
0|drone-ud | Creating a pool connected to localhost:28015

/home/ubuntu/.pm2/logs/gcs-tcp-server-error.log last 15 lines:
2|gcs-tcp- | Creating a pool connected to localhost:28015
2|gcs-tcp- | Creating a pool connected to localhost:28015
2|gcs-tcp- | Creating a pool connected to localhost:28015
2|gcs-tcp- | Creating a pool connected to localhost:28015
2|gcs-tcp- | Creating a pool connected to localhost:28015
2|gcs-tcp- | Creating a pool connected to localhost:28015

/home/ubuntu/.pm2/logs/drone-udp-server-out.log last 15 lines:
0|drone-ud | Background saving started
0|drone-ud | Redis is ready
0|drone-ud | Redis is ready
0|drone-ud | warn: STOPPING UDP SERVER
0|drone-ud | Background saving started
0|drone-ud | Redis is ready
0|drone-ud | Redis is ready
0|drone-ud | warn: STOPPING UDP SERVER
0|drone-ud | Background saving started
0|drone-ud | Redis is ready
0|drone-ud | Redis is ready
0|drone-ud | warn: STOPPING UDP SERVER
0|drone-ud | Background saving started
0|drone-ud | Redis is ready
0|drone-ud | Redis is ready

/home/ubuntu/.pm2/logs/gcs-tcp-server-out.log last 15 lines:
2|gcs-tcp- | Redis is ready
2|gcs-tcp- | Redis is ready
2|gcs-tcp- | Redis is ready
2|gcs-tcp- | Redis is ready
2|gcs-tcp- | Redis is ready
2|gcs-tcp- | Redis is ready
2|gcs-tcp- | Redis is ready
2|gcs-tcp- | Redis is ready
2|gcs-tcp- | Redis is ready
2|gcs-tcp- | Redis is ready
2|gcs-tcp- | Redis is ready
2|gcs-tcp- | Redis is ready

/home/ubuntu/.pm2/logs/drones-server-error.log last 15 lines:
1|drones-s |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
1|drones-s |     at Module.load (internal/modules/cjs/loader.js:863:32)
1|drones-s |     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
1|drones-s |     at Module.require (internal/modules/cjs/loader.js:887:19)
1|drones-s |     at Module.Hook._require.Module.require (/usr/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39)
1|drones-s |     at require (internal/modules/cjs/helpers.js:74:18)
1|drones-s |     at Object.<anonymous> (/home/ubuntu/gcs_uno_server/node_modules/@google/maps/lib/index.js:108:16)
1|drones-s |     at Module._compile (internal/modules/cjs/loader.js:999:30)
1|drones-s |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
1|drones-s |     at Module.load (internal/modules/cjs/loader.js:863:32)
1|drones-s |     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
1|drones-s |     at Module.require (internal/modules/cjs/loader.js:887:19)
1|drones-s |     at Module.Hook._require.Module.require (/usr/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39) {
1|drones-s |   code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
1|drones-s | }

/home/ubuntu/.pm2/logs/io-server-error.log last 15 lines:
3|io-serve |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
3|io-serve |     at Module.load (internal/modules/cjs/loader.js:863:32)
3|io-serve |     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
3|io-serve |     at Module.require (internal/modules/cjs/loader.js:887:19)
3|io-serve |     at Module.Hook._require.Module.require (/usr/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39)
3|io-serve |     at require (internal/modules/cjs/helpers.js:74:18)
3|io-serve |     at Object.<anonymous> (/home/ubuntu/gcs_uno_server/node_modules/@google/maps/lib/index.js:108:16)
3|io-serve |     at Module._compile (internal/modules/cjs/loader.js:999:30)
3|io-serve |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
3|io-serve |     at Module.load (internal/modules/cjs/loader.js:863:32)
3|io-serve |     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
3|io-serve |     at Module.require (internal/modules/cjs/loader.js:887:19)
3|io-serve |     at Module.Hook._require.Module.require (/usr/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39) {
3|io-serve |   code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
3|io-serve | }
```

I wish to provide feedback to update online docs to install it, because these are outdated. Also there are critical vulnerabilities as a NODE.js dependency that must be cleared to avoid issues. Is this something that one can easy work around the above error? 

Is there some simillar software on market to replace gcs? Amazing tool, pitty is not mantained in 2 years, that is a lot in todays fast pacing internet.

node.js its on release 14.x 
ubuntu its on 20.10
and so on...

There are bad instructions some of them in the site, some misstypos, i wont report those until I figure out the status of the project. I see no issues opened, not much Stars nor a community evolving around it, so if its no demand i wont share more. And will look for alternatives. 

Thanks!

**Comment by uhlhosting** [comment]
https://github.com/uuidjs/uuid/blob/master/CHANGELOG.md#-breaking-changes related to above uuid.v4 = v4; error. This was deprecated.

**Comment by DobriyDed** [comment]
file:     node_modules/@google/maps/package.json
 line 47
 replace  "uuid": ">=2.2.1"
by   "uuid": "^3.4.0"
so it looks like :


   "dependencies": {
     "uuid": "^3.4.0"
   },


Then, from project dir (gcs_uno_server) run:
`npm uninstall uuid`
`npm install`
`cd servers`
Run servers ( pm2  start ....) as described in manual
It works now, but can be "ruined" later
